### ISSUE TITLE
Errors on second getFile after transactions

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/ai-portland-rocketleague#1]
I consistently get this following this scenario

1) upload a file via uploadFile, wait for state to be ACTIVE (10s video)
2) .getFile(fileName);, check state is ACTIVE before step 3
3) use the file with genAI
            .getGenerativeModel({ model: "gemini-2.0-flash-exp" })
            .generateContent(...
 4) call deleteFile from step 2 after response
 5) try to upload another file....  always the same 500 ISE 
 
 
 ```
GoogleGenerativeAIFetchError: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/files/9xe0iylwxcur: [500 Internal Server Error] Failed to convert server response to JSON
    at handleResponseNotOk (file:///mnt/c/Users/scott/Documents/workspace/ai-portland-rocketleague/ScreenShareFeedback/node_modules/@google/generative-ai/dist/server/index.mjs:127:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async makeRequest (file:///mnt/c/Users/scott/Documents/workspace/ai-portland-rocketleague/ScreenShareFeedback/node_modules/@google/generative-ai/dist/server/index.mjs:100:9)
    at async GoogleAIFileManager.getFile (file:///mnt/c/Users/scott/Documents/workspace/ai-portland-rocketleague/ScreenShareFeedback/node_modules/@google/generative-ai/dist/server/index.mjs:352:26)
    at async checkProgress (file:///mnt/c/Users/scott/Documents/workspace/ai-portland-rocketleague/ScreenShareFeedback/server/upload.mjs:58:20)
    at async file:///mnt/c/Users/scott/Documents/workspace/ai-portland-rocketleague/ScreenShareFeedback/server/index.mjs:38:22 {
  status: 500,
  statusText: 'Internal Server Error',
  errorDetails: undefined
```

**Comment by denieve** [comment]
no longer using this in the presentation given timeline/bug
